ci: move dev-staging merge to `deploy-staging.yml`

diff --git a/.github/workflows/deploy-staging.yml b/.github/workflows/deploy-staging.yml
--- a/.github/workflows/deploy-staging.yml
+++ b/.github/workflows/deploy-staging.yml
@@ -15,9 +15,34 @@ on:
           - backend
 
 jobs:
+  merge-dev-to-staging:
+    name: Fast-Forward Merge dev to staging
+    runs-on: ubuntu-${{ vars.RUNNER_VERSION }}
+
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0 # Ensure full history is fetched for merging
+
+      - name: Configure Git
+        run: |
+          git config user.name "github-actions[bot]"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
+
+      - name: Fast-Forward Merge
+        run: |
+          git checkout staging
+          git merge --ff-only origin/dev || {
+            echo "Fast-forward merge failed. Ensure dev branch is up-to-date.";
+            exit 1;
+          }
+          git push origin staging
+
   build:
     name: Set yarn and build artifacts
     runs-on: ubuntu-${{vars.RUNNER_VERSION}}
+    needs: merge-dev-to-staging
     outputs:
       yarn_version: ${{ steps.set_yarn_version.outputs.yarn_version }}
     environment: staging
diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -382,39 +382,38 @@ jobs:
           command: pages deploy packages/backend/dist --project-name=backend
           gitHubToken: ${{ secrets.GITHUB_TOKEN }}
 
-  merge-dev-to-staging:
-    name: Fast-Forward Merge dev to staging
-    if: ${{ github.event_name == 'push' && github.ref_name == 'dev' }}
-    needs: deploy-development
-    runs-on: ubuntu-${{ vars.RUNNER_VERSION }}
+  # merge-dev-to-staging:
+  #   name: Fast-Forward Merge dev to staging
+  #   if: ${{ github.event_name == 'push' && github.ref_name == 'dev' }}
+  #   needs: deploy-development
+  #   runs-on: ubuntu-${{ vars.RUNNER_VERSION }}
 
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0 # Ensure full history is fetched for merging
+  #   steps:
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0 # Ensure full history is fetched for merging
 
-      - name: Configure Git
-        run: |
-          git config user.name "github-actions[bot]"
-          git config user.email "github-actions[bot]@users.noreply.github.com"
+  #     - name: Configure Git
+  #       run: |
+  #         git config user.name "github-actions[bot]"
+  #         git config user.email "github-actions[bot]@users.noreply.github.com"
 
-      - name: Fast-Forward Merge
-        run: |
-          git checkout staging
-          git merge --ff-only origin/dev || {
-            echo "Fast-forward merge failed. Ensure dev branch is up-to-date.";
-            exit 1;
-          }
-          git push origin staging
+  #     - name: Fast-Forward Merge
+  #       run: |
+  #         git checkout staging
+  #         git merge --ff-only origin/dev || {
+  #           echo "Fast-forward merge failed. Ensure dev branch is up-to-date.";
+  #           exit 1;
+  #         }
+  #         git push origin staging
 
   all-green:
     name: All Green
     if: always()
     runs-on: ubuntu-${{ vars.RUNNER_VERSION }}
     environment: development
-    needs:
-      [
+    needs: [
         build,
         test-unit,
         test-comp,
@@ -422,7 +421,7 @@ jobs:
         test-func,
         test-e2e,
         deploy-development,
-        merge-dev-to-staging,
+        # merge-dev-to-staging,
       ]
 
     steps:
