CI fix staging deployment (#224)

diff --git a/.github/workflows/deploy-staging.yml b/.github/workflows/deploy-staging.yml
--- a/.github/workflows/deploy-staging.yml
+++ b/.github/workflows/deploy-staging.yml
@@ -1,45 +1,51 @@
-name: Deploy staging
+# Deploys frontend or backend to staging environment.
+
+name: Deploy to Staging
 
 on:
-  push:
-    branches: ['staging']
   workflow_dispatch:
+    inputs:
+      deployment_target:
+        description: 'Select deployment (frontend or backend)'
+        required: true
+        default: 'frontend'
+        type: choice
+        options:
+          - frontend
+          - backend
 
 jobs:
-  changes:
-    name: Check changes
-    runs-on: ubuntu-${{vars.RUNNER_VERSION}}
-    permissions:
-      pull-requests: read
-    outputs:
-      frontend: ${{ steps.filter.outputs.frontend }}
-      backend: ${{ steps.filter.outputs.backend }}
+  merge-dev-to-staging:
+    name: Fast-Forward Merge dev to staging
+    runs-on: ubuntu-${{ vars.RUNNER_VERSION }}
+
     steps:
-      - uses: actions/checkout@v4
-      - uses: dorny/paths-filter@v3
-        id: filter
+      - name: Checkout Repository
+        uses: actions/checkout@v4
         with:
-          base: dev
-          # base: ${{ github.ref_name }}
-          list-files: csv
-          filters: |
-            frontend:
-              - 'packages/frontend/**'
-            backend:
-              - 'packages/backend/**'
-      - name: Log all filter results
+          fetch-depth: 0 # Ensure full history is fetched for merging
+
+      - name: Configure Git
         run: |
-          echo "frontend: ${{ steps.filter.outputs.frontend }}"
-          echo "backend: ${{ steps.filter.outputs.backend }}"
+          git config user.name "github-actions[bot]"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
+
+      - name: Fast-Forward Merge
+        run: |
+          git checkout staging
+          git merge --ff-only origin/dev || {
+            echo "Fast-forward merge failed. Ensure dev branch is up-to-date.";
+            exit 1;
+          }
+          git push origin staging
 
   build:
     name: Set yarn and build artifacts
     runs-on: ubuntu-${{vars.RUNNER_VERSION}}
+    needs: merge-dev-to-staging
     outputs:
       yarn_version: ${{ steps.set_yarn_version.outputs.yarn_version }}
-    needs: [changes]
     environment: staging
-    if: ${{ needs.changes.outputs.backend == 'true' || needs.changes.outputs.frontend == 'true' }}
     steps:
       - uses: actions/checkout@v4
 
@@ -61,12 +67,12 @@ jobs:
           yarn-version: ${{ steps.set_yarn_version.outputs.yarn_version }}
           yarn-install-cache-key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
 
-      - name: Build frontend for staging
-        if: ${{ needs.changes.outputs.frontend == 'true' }}
+      - name: Build frontend for development
+        if: ${{ inputs.deployment_target == 'frontend' }}
         run: yarn workspace frontend build:staging
 
-      - name: Build backend for staging
-        if: ${{ needs.changes.outputs.backend == 'true' }}
+      - name: Build backend for development
+        if: ${{ inputs.deployment_target == 'backend' }}
         run: yarn workspace backend build
 
       # Cache the build after all is said and done.
@@ -77,15 +83,13 @@ jobs:
           path: ./*
           key: ${{ github.sha }}-${{ github.run_number }}
 
-  deploy-staging:
-    name: Deploy to development environment
-    needs: [build, changes]
-    if: ${{ github.event_name == 'push' && github.ref_name == 'dev' }}
+  deploy:
+    name: Deploy target
+    runs-on: ubuntu-${{vars.RUNNER_VERSION}}
+    needs: build
     env:
       YARN_VERSION: ${{ needs.build.outputs.yarn_version }}
-    runs-on: ubuntu-${{ vars.RUNNER_VERSION }}
     environment: staging
-
     steps:
       - uses: actions/checkout@v4
 
@@ -105,7 +109,7 @@ jobs:
           key: ${{ github.sha }}-${{ github.run_number }}
 
       - name: Publish frontend to Cloudflare Pages
-        if: ${{ needs.changes.outputs.frontend == 'true' }}
+        if: ${{ inputs.deployment_target == 'frontend' }}
         uses: cloudflare/wrangler-action@v3
         with:
           apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
@@ -114,3 +118,11 @@ jobs:
           gitHubToken: ${{ secrets.GITHUB_TOKEN }}
 
       # Deploy backend artifact
+      - name: Publish backend to Cloudflare Pages
+        if: ${{ inputs.deployment_target == 'backend' }}
+        uses: cloudflare/wrangler-action@v3
+        with:
+          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
+          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
+          command: pages deploy packages/backend/dist --project-name=backend
+          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,6 @@
-name: 'Staging'
+# Main development workflow.
+
+name: 'Dev'
 
 on:
   push:
@@ -380,130 +382,38 @@ jobs:
           command: pages deploy packages/backend/dist --project-name=backend
           gitHubToken: ${{ secrets.GITHUB_TOKEN }}
 
-  merge-dev-to-staging:
-    name: Fast-Forward Merge dev to staging
-    if: ${{ github.event_name == 'push' && github.ref_name == 'dev' }}
-    needs: deploy-development
-    runs-on: ubuntu-${{ vars.RUNNER_VERSION }}
+  # merge-dev-to-staging:
+  #   name: Fast-Forward Merge dev to staging
+  #   if: ${{ github.event_name == 'push' && github.ref_name == 'dev' }}
+  #   needs: deploy-development
+  #   runs-on: ubuntu-${{ vars.RUNNER_VERSION }}
 
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0 # Ensure full history is fetched for merging
+  #   steps:
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0 # Ensure full history is fetched for merging
 
-      - name: Configure Git
-        run: |
-          git config user.name "github-actions[bot]"
-          git config user.email "github-actions[bot]@users.noreply.github.com"
+  #     - name: Configure Git
+  #       run: |
+  #         git config user.name "github-actions[bot]"
+  #         git config user.email "github-actions[bot]@users.noreply.github.com"
 
-      - name: Fast-Forward Merge
-        run: |
-          git checkout staging
-          git merge --ff-only origin/dev || {
-            echo "Fast-forward merge failed. Ensure dev branch is up-to-date.";
-            exit 1;
-          }
-          git push origin staging
-
-  build-staging:
-    name: Set yarn and build artifacts
-    runs-on: ubuntu-${{vars.RUNNER_VERSION}}
-    outputs:
-      yarn_version: ${{ steps.set_yarn_version.outputs.yarn_version }}
-    needs: [changes, merge-dev-to-staging]
-    environment: staging
-    if: ${{ needs.changes.outputs.backend == 'true' || needs.changes.outputs.frontend == 'true' }}
-    steps:
-      - uses: actions/checkout@v4
-
-      # Retrieve yarn version from package.json
-      - name: Get yarn version from package.json
-        run: |
-          grep 'packageManager' package.json | awk -F: '{gsub(/[", ]/, "", $2); print $2}' | xargs -I {} echo "YARN_VERSION="{} >> "$GITHUB_ENV"
-
-      # Set the yarn version by exporting to env var and output
-      - name: Append yarn version to $GITHUB_OUTPUT
-        id: set_yarn_version
-        run: |
-          echo "yarn_version=${{ env.YARN_VERSION }}" >> "$GITHUB_OUTPUT"
-
-      - name: Node setup
-        uses: ./.github/actions/setup
-        with:
-          node-version: ${{ vars.NODE_VERSION }}
-          yarn-version: ${{ steps.set_yarn_version.outputs.yarn_version }}
-          yarn-install-cache-key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
-
-      - name: Build frontend for staging
-        if: ${{ needs.changes.outputs.frontend == 'true' && (github.event_name == 'push' && github.ref_name == 'dev') }}
-        run: yarn workspace frontend build:staging
-
-      - name: Build backend for staging
-        if: ${{ needs.changes.outputs.backend == 'true' && (github.event_name == 'push' && github.ref_name == 'dev') }}
-        run: yarn workspace backend build
-
-      # Cache the build after all is said and done.
-      # This build will be used in the following jobs.
-      - name: Cache build
-        uses: actions/cache@v4
-        with:
-          path: ./*
-          key: ${{ github.sha }}-${{ github.run_number }}
-
-  deploy-staging:
-    name: Deploy to staging environment
-    if: ${{ github.event_name == 'push' && github.ref_name == 'dev' }}
-    env:
-      YARN_VERSION: ${{ needs.build-staging.outputs.yarn_version }}
-    runs-on: ubuntu-${{ vars.RUNNER_VERSION }}
-    environment: staging
-    needs: [changes, build-staging]
-
-    steps:
-      - uses: actions/checkout@v4
-
-      - name: Node setup
-        uses: ./.github/actions/setup
-        with:
-          node-version: ${{ vars.NODE_VERSION }}
-          yarn-version: ${{ env.YARN_VERSION  }}
-          yarn-run-install: false
-          yarn-restore-cache: false # We restore the build from actions/cache
-          yarn-install-cache-key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
-
-      - name: Restore build
-        uses: actions/cache@v4
-        with:
-          path: ./*
-          key: ${{ github.sha }}-${{ github.run_number }}
-
-      - name: Publish frontend to Cloudflare Pages
-        if: ${{ needs.changes.outputs.frontend == 'true' }}
-        uses: cloudflare/wrangler-action@v3
-        with:
-          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
-          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
-          command: pages deploy packages/frontend/.svelte-kit/cloudflare --project-name=website
-          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
-
-      # Deploy backend artifact
-      - name: Publish backend to Cloudflare Pages
-        if: ${{ needs.changes.outputs.backend == 'true' }}
-        uses: cloudflare/wrangler-action@v3
-        with:
-          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
-          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
-          command: pages deploy packages/backend/dist --project-name=backend
-          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Fast-Forward Merge
+  #       run: |
+  #         git checkout staging
+  #         git merge --ff-only origin/dev || {
+  #           echo "Fast-forward merge failed. Ensure dev branch is up-to-date.";
+  #           exit 1;
+  #         }
+  #         git push origin staging
 
   all-green:
     name: All Green
     if: always()
     runs-on: ubuntu-${{ vars.RUNNER_VERSION }}
     environment: development
-    needs:
-      [
+    needs: [
         build,
         test-unit,
         test-comp,
@@ -511,7 +421,7 @@ jobs:
         test-func,
         test-e2e,
         deploy-development,
-        merge-dev-to-staging,
+        # merge-dev-to-staging,
       ]
 
     steps:
