refactor(ci): deploy to staging in `main.yml`
Deploy to staging env in `main.yml`. Circumvents the `staging` branch
for quicker iteration. There is no need for a staging branch anyway.
Staging really only applies to the dataset, which is separate from the
code.

diff --git a/.github/workflows/push-to-main.yml b/.github/workflows/push-to-main.yml
--- a/.github/workflows/push-to-main.yml
+++ b/.github/workflows/push-to-main.yml
@@ -24,8 +24,8 @@ jobs:
       - name: Fast-Forward Merge
         run: |
           git checkout main
-          git merge --ff-only origin/staging || {
-            echo "Fast-forward merge failed. Ensure staging branch is up-to-date.";
+          git merge --ff-only origin/dev || {
+            echo "Fast-forward merge failed. Ensure dev branch is up-to-date.";
             exit 1;
           }
           git push origin main
